### ISSUE TITLE
Make scrollbars change with theme

### ISSUE THREAD

**Issue by woellie123** [basmilius/latte-ui#17]
Since Firefox does not (at the moment) support custom scrollbars like Chrome, it would be nice if something like the class below would be implemented to simulate custom scrollbars:

```css
.custom-scrollbar {
  scrollbar-width: thin;
  scrollbar-color: thumbColor trackColor;
}
```

**Comment by woellie123** [comment]
Please consider the following CSS implementation (it looks pretty much the same on Firefox and webkit based browsers)

```css
* {
    scrollbar-width: thin !important;
    scrollbar-color: #494949 #1B1B1B;
}

::-webkit-scrollbar {
  width: 8px;
}

::-webkit-scrollbar-track {
    background: #1B1B1B;
}
 
::-webkit-scrollbar-thumb {
    background: #494949;
}

::-webkit-scrollbar-thumb:hover {
    background: #5C5C5C;
}

::-webkit-scrollbar-thumb:active {
    background: #9F9F9F;
}
```
